<?php

/**
 * Sri Lanka Administrative Divisions
 * 
 * Hierarchical mapping: Province → District → DS Divisions
 */

$hierarchy = [
    // ─── CENTRAL PROVINCE ────────────────────────────────────────
    'Central' => [
        'Kandy' => [
            'Akurana',
            'Delthota',
            'Doluwa',
            'Ganga Ihala Korale',
            'Harispattuwa',
            'Hatharaliyadda',
            'Kandy Four Gravets & Gangawata Korale',
            'Kundasale',
            'Medadumbara',
            'Minipe',
            'Panvila',
            'Pasbage Korale',
            'Pathadumbara',
            'Pathahewaheta',
            'Poojapitiya',
            'Thumpane',
            'Udadumbara',
            'Udapalatha',
            'Udunuwara',
            'Yatinuwara',
        ],
        'Matale' => [
            'Ambanganga Korale',
            'Dambulla',
            'Galewela',
            'Laggala-Pallegama',
            'Matale',
            'Naula',
            'Pallepola',
            'Rattota',
            'Ukuwela',
            'Wilgamuwa',
            'Yatawatta',
        ],
        'Nuwara Eliya' => [
            'Ambagamuwa',
            'Hanguranketha',
            'Kothmale',
            'Nuwara Eliya',
            'Walapane',
        ],
    ],

    // ─── EASTERN PROVINCE ────────────────────────────────────────
    'Eastern' => [
        'Ampara' => [
            'Addalachchenai',
            'Akkaraipattu',
            'Alayadiwembu',
            'Ampara',
            'Damana',
            'Dehiattakandiya',
            'Eragama',
            'Kalmunai',
            'Karativu',
            'Lahugala',
            'Mahaoya',
            'Navithanveli',
            'Ninthavur',
            'Padiyathalawa',
            'Pothuvil',
            'Sainthamarathu',
            'Samanthurai',
            'Thirukkovil',
            'Uhana',
        ],
        'Batticaloa' => [
            'Eravur Pattu',
            'Eravur Town',
            'Kattankudy',
            'Koralai Pattu (Valachchenai)',
            'Koralai Pattu Central',
            'Koralai Pattu North',
            'Koralai Pattu South (Kiran)',
            'Koralai Pattu West (Oddamavadi)',
            'Manmunai North',
            'Manmunai Pattu (Araipattai)',
            'Manmunai South & Eruvil Pattu',
            'Manmunai South-West',
            'Manmunai West',
            'Porativu Pattu',
        ],
        'Trincomalee' => [
            'Gomarankadawala',
            'Kantalai',
            'Kinniya',
            'Kuchchaveli',
            'Morawewa',
            'Muttur',
            'Padavi Sri Pura',
            'Seruvila',
            'Thambalagamuwa',
            'Trincomalee Town and Gravets',
            'Verugal (Eechchilampattai)',
        ],
    ],

    // ─── NORTH CENTRAL PROVINCE ──────────────────────────────────
    'North Central' => [
        'Anuradhapura' => [
            'Galenbindunuwewa',
            'Galnewa',
            'Horowpothana',
            'Ipalogama',
            'Kahatagasdigiliya',
            'Kebithigollewa',
            'Kekirawa',
            'Mahavilachchiya',
            'Medawachchiya',
            'Mihinthale',
            'Nachchadoowa',
            'Nochchiyagama',
            'Nuwaragam Palatha Central',
            'Nuwaragam Palatha East',
            'Padaviya',
            'Palagala',
            'Palugaswewa',
            'Rajanganaya',
            'Rambewa',
            'Thalawa',
            'Thambuttegama',
            'Thirappane',
        ],
        'Polonnaruwa' => [
            'Dimbulagala',
            'Elahera',
            'Hingurakgoda',
            'Lankapura',
            'Medirigiriya',
            'Thamankaduwa',
            'Welikanda',
        ],
    ],

    // ─── NORTHERN PROVINCE ───────────────────────────────────────
    'Northern' => [
        'Jaffna' => [
            'Delft',
            'Island North (Kayts)',
            'Island South (Velanai)',
            'Jaffna',
            'Karainagar',
            'Nallur',
            'Thenmaradchi (Chavakachcheri)',
            'Vadamaradchi East (Maruthnkerny)',
            'Vadamaradchi North (Point Pedro)',
            'Vadamaradchi South-West (Karaveddy)',
            'Valikamam East (Kopay)',
            'Valikamam North (Tellipallai)',
            'Valikamam South (Uduvil)',
            'Valikamam South-West (Sandilipay)',
            'Valikamam West (Chankanai)',
        ],
        'Kilinochchi' => [
            'Kandavalai',
            'Karachchi',
            'Pachchilaipalli',
            'Poonakary',
        ],
        'Mannar' => [
            'Madhu',
            'Mannar Town',
            'Manthai West',
            'Musalai',
            'Nanaddan',
        ],
        'Mullaitivu' => [
            'Manthai East',
            'Maritimepattu',
            'Oddusuddan',
            'Puthukudiyiruppu',
            'Thunukkai',
            'Welioya',
        ],
        'Vavuniya' => [
            'Vavuniya',
            'Vavuniya North',
            'Vavuniya South',
            'Vengalacheddikulam',
        ],
    ],

    // ─── NORTH WESTERN PROVINCE ──────────────────────────────────
    'North Western' => [
        'Kurunegala' => [
            'Alawwa',
            'Ambanpola',
            'Bamunakotuwa',
            'Bingiriya',
            'Ehetuwewa',
            'Galgamuwa',
            'Ganewatta',
            'Giribawa',
            'Ibbagamuwa',
            'Katupotha',
            'Kobeigane',
            'Kotavehera',
            'Kuliyapitiya East',
            'Kuliyapitiya West',
            'Kurunegala',
            'Mahawa',
            'Maho',
            'Mallawapitiya',
            'Maspotha',
            'Mawathagama',
            'Narammala',
            'Nikaweratiya',
            'Panduwasnuwara',
            'Pannala',
            'Polgahawela',
            'Polpithigama',
            'Rasnayakapura',
            'Rideegama',
            'Udubaddawa',
            'Wariyapola',
            'Weerambugedara',
        ],
        'Puttalam' => [
            'Anamaduwa',
            'Arachchikattuwa',
            'Chilaw',
            'Dankotuwa',
            'Kalpitiya',
            'Karuwalagaswewa',
            'Madampe',
            'Mahakumbukkadawala',
            'Mahawewa',
            'Mundalama',
            'Nattandiya',
            'Nawagattegama',
            'Pallama',
            'Puttalam',
            'Vanathavilluwa',
            'Wennappuwa',
        ],
    ],

    // ─── SABARAGAMUWA PROVINCE ───────────────────────────────────
    'Sabaragamuwa' => [
        'Kegalle' => [
            'Aranayaka',
            'Bulathkohupitiya',
            'Dehiovita',
            'Deraniyagala',
            'Galigamuwa',
            'Kegalle',
            'Mawanella',
            'Rambukkana',
            'Ruwanwella',
            'Warakapola',
            'Yatiyanthota',
        ],
        'Ratnapura' => [
            'Ayagama',
            'Balangoda',
            'Eheliyagoda',
            'Elapatha',
            'Embilipitiya',
            'Godakawela',
            'Imbulpe',
            'Kahawatta',
            'Kalawana',
            'Kiriella',
            'Kolonna',
            'Kuruwita',
            'Nivithigala',
            'Opanayaka',
            'Pelmadulla',
            'Ratnapura',
            'Weligepola',
        ],
    ],

    // ─── SOUTHERN PROVINCE ───────────────────────────────────────
    'Southern' => [
        'Galle' => [
            'Akmeemana',
            'Ambalangoda',
            'Baddegama',
            'Balapitiya',
            'Benthota',
            'Bope-Poddala',
            'Elpitiya',
            'Galle Four Gravets',
            'Gonapinuwala',
            'Habaraduwa',
            'Hikkaduwa',
            'Imaduwa',
            'Karandeniya',
            'Nagoda',
            'Neluwa',
            'Niyagama',
            'Thawalama',
            'Welivitiya-Divithura',
            'Yakkalamulla',
        ],
        'Hambantota' => [
            'Ambalantota',
            'Angunakolapelessa',
            'Beliatta',
            'Hambantota',
            'Katuwana',
            'Lunugamvehera',
            'Okewela',
            'Sooriyawewa',
            'Tangalle',
            'Thissamaharama',
            'Walasmulla',
            'Weeraketiya',
        ],
        'Matara' => [
            'Akuressa',
            'Athuraliya',
            'Devinuwara',
            'Dickwella',
            'Hakmana',
            'Kamburupitiya',
            'Kirinda Puhulwella',
            'Kotapola',
            'Malimbada',
            'Matara Four Gravets',
            'Mulatiyana',
            'Pasgoda',
            'Pitabeddara',
            'Thihagoda',
            'Weligama',
            'Welipitiya',
        ],
    ],

    // ─── UVA PROVINCE ────────────────────────────────────────────
    'Uva' => [
        'Badulla' => [
            'Badulla',
            'Bandarawela',
            'Ella',
            'Haldummulla',
            'Hali-Ela',
            'Haputale',
            'Kandaketiya',
            'Lunugala',
            'Mahiyanganaya',
            'Meegahakivula',
            'Passara',
            'Rideemaliyadda',
            'Soranathota',
            'Uva-Paranagama',
            'Welimada',
        ],
        'Moneragala' => [
            'Badalkumbura',
            'Bibile',
            'Buttala',
            'Katharagama',
            'Madulla',
            'Medagama',
            'Moneragala',
            'Sevanagala',
            'Siyambalanduwa',
            'Thanamalvila',
            'Wellawaya',
        ],
    ],

    // ─── WESTERN PROVINCE ────────────────────────────────────────
    'Western' => [
        'Colombo' => [
            'Colombo',
            'Dehiwala-Mount Lavinia',
            'Hanwella',
            'Homagama',
            'Kaduwela',
            'Kesbewa',
            'Kolonnawa',
            'Maharagama',
            'Moratuwa',
            'Padukka',
            'Ratmalana',
            'Seethawaka',
            'Sri Jayawardanapura Kotte',
            'Thimbirigasyaya',
        ],
        'Gampaha' => [
            'Attanagalla',
            'Biyagama',
            'Divulapitiya',
            'Dompe',
            'Gampaha',
            'Ja-Ela',
            'Katana',
            'Kelaniya',
            'Mahara',
            'Minuwangoda',
            'Mirigama',
            'Negombo',
            'Wattala',
        ],
        'Kalutara' => [
            'Agalawatta',
            'Bandaragama',
            'Beruwala',
            'Bulathsinhala',
            'Dodangoda',
            'Horana',
            'Ingiriya',
            'Kalutara',
            'Madurawela',
            'Mathugama',
            'Millaniya',
            'Palindanuwara',
            'Panadura',
            'Walallavita',
        ],
    ],
];

// ─── AUTO-GENERATED FLAT LISTS (for backward compatibility) ─────
// These are derived from the hierarchy above.

// get provinces from hierarchy
$provinces  = array_keys($hierarchy);

// initialize districts and dsDivisions
$districts  = [];
$dsDivisions = [];

// get districts and dsDivisions from hierarchy
foreach ($hierarchy as $province => $districtMap) {
    foreach ($districtMap as $district => $divisions) {
        $districts[]  = $district;
        $dsDivisions  = array_merge($dsDivisions, $divisions);
    }
}

sort($districts);
sort($dsDivisions);

return [
    'hierarchy'    => $hierarchy,
    'provinces'    => $provinces,
    'districts'    => $districts,
    'ds_divisions' => $dsDivisions,
];
