<?php

return [
    'provinces' => [
        'Central',
        'Eastern',
        'North Central',
        'Northern',
        'North Western',
        'Sabaragamuwa',
        'Southern',
        'Uva',
        'Western',
    ],

    'districts' => [
        'Ampara',
        'Anuradhapura',
        'Badulla',
        'Batticaloa',
        'Colombo',
        'Galle',
        'Gampaha',
        'Hambantota',
        'Jaffna',
        'Kalutara',
        'Kandy',
        'Kegalle',
        'Kilinochchi',
        'Kurunegala',
        'Mannar',
        'Matale',
        'Matara',
        'Moneragala',
        'Mullaitivu',
        'Nuwara Eliya',
        'Polonnaruwa',
        'Puttalam',
        'Ratnapura',
        'Trincomalee',
        'Vavuniya',
    ],

    'ds_divisions' => [
        'Addalachchenai',
        'Agalawatta',
        'Akkaraipattu',
        'Akmeemana',
        'Akurana',
        'Akuressa',
        'Alawwa',
        'Alayadiwembu',
        'Ambagamuwa',
        'Ambalangoda',
        'Ambalantota',
        'Ambanganga Korale',
        'Ambanpola',
        'Ampara',
        'Anamaduwa',
        'Angunakolapelessa',
        'Arachchikattuwa',
        'Aranayaka',
        'Athuraliya',
        'Attanagalla',
        'Ayagama',
        'Badalkumbura',
        'Baddegama',
        'Badulla',
        'Balangoda',
        'Balapitiya',
        'Bamunakotuwa',
        'Bandaragama',
        'Bandarawela',
        'Beliatta',
        'Benthota',
        'Beruwala',
        'Bibile',
        'Bingiriya',
        'Biyagama',
        'Bope-Poddala',
        'Bulathkohupitiya',
        'Bulathsinhala',
        'Buttala',
        'Chilaw',
        'Colombo',
        'Damana',
        'Dambulla',
        'Dankotuwa',
        'Dehiattakandiya',
        'Dehiovita',
        'Dehiwala-Mount Lavinia',
        'Delft',
        'Delthota',
        'Deraniyagala',
        'Devinuwara',
        'Dickwella',
        'Dimbulagala',
        'Divulapitiya',
        'Dodangoda',
        'Doluwa',
        'Dompe',
        'Eheliyagoda',
        'Ehetuwewa',
        'Elahera',
        'Elapatha',
        'Ella',
        'Elpitiya',
        'Embilipitiya',
        'Eragama',
        'Eravur Pattu',
        'Eravur Town',
        'Galenbindunuwewa',
        'Galewela',
        'Galgamuwa',
        'Galigamuwa',
        'Galle Four Gravets',
        'Galnewa',
        'Gampaha',
        'Ganewatta',
        'Ganga Ihala Korale',
        'Giribawa',
        'Godakawela',
        'Gomarankadawala',
        'Habaraduwa',
        'Hakmana',
        'Haldummulla',
        'Hali-Ela',
        'Hambantota',
        'Hanguranketha',
        'Hanwella',
        'Haputale',
        'Harispattuwa',
        'Hatharaliyadda',
        'Hikkaduwa',
        'Hingurakgoda',
        'Homagama',
        'Horana',
        'Horowpothana',
        'Ibbagamuwa',
        'Imaduwa',
        'Imbulpe',
        'Ingiriya',
        'Ipalogama',
        'Island North (Kayts)',
        'Island South (Velanai)',
        'Ja-Ela',
        'Jaffna',
        'Kaduwela',
        'Kahatagasdigiliya',
        'Kahawatta',
        'Kalawana',
        'Kalmunai',
        'Kalpitiya',
        'Kalutara',
        'Kamburupitiya',
        'Kandaketiya',
        'Kandavalai',
        'Kandy Four Gravets &amp; Gangawata Korale',
        'Kantalai',
        'Karachchi',
        'Karandeniya',
        'Karativu',
        'Karuwalagaswewa',
        'Katana',
        'Katharagama',
        'Kattankudy',
        'Katupotha',
        'Katuwana',
        'Kebithigollewa',
        'Kegalle',
        'Kekirawa',
        'Kelaniya',
        'Kesbewa',
        'Kinniya',
        'Kiriella',
        'Kirinda Puhulwella',
        'Kobeigane',
        'Kolonna',
        'Kolonnawa',
        'Koralai Pattu (Valachchenai)',
        'Koralai Pattu North',
        'Koralai Pattu South (Kiran)',
        'Koralai Pattu West (Oddamavadi)',
        'Kotapola',
        'Kotavehera',
        'Kothmale',
        'Kuchchaveli',
        'Kuliyapitiya East',
        'Kuliyapitiya West',
        'Kundasale',
        'Kurunegala',
        'Kuruvita',
        'Laggala-Pallegama',
        'Lahugala',
        'Lankapura',
        'Lunugala',
        'Lunugamvehera',
        'Madampe',
        'Madhu',
        'Madulla',
        'Madurawela',
        'Mahakumbukkadawala',
        'Mahaoya',
        'Mahara',
        'Maharagama',
        'Mahavilachchiya',
        'Mahawa',
        'Mahawewa',
        'Mahiyanganaya',
        'Malimbada',
        'Mallawapitiya',
        'Manmunai North',
        'Manmunai Pattu (Araipattai)',
        'Manmunai South,Eruvil Pattu',
        'Manmunai South-West',
        'Manmunai West',
        'Mannar Town',
        'Manthai East',
        'Manthai West',
        'Maritimepattu',
        'Maspotha',
        'Matale',
        'Matara Four Gravets',
        'Mathugama',
        'Mawanella',
        'Mawathagama',
        'Medadumbara',
        'Medagama',
        'Medawachchiya',
        'Medirigiriya',
        'Meegahakivula',
        'Mihinthale',
        'Millaniya',
        'Minipe',
        'Minuwangoda',
        'Mirigama',
        'Moneragala',
        'Moratuwa',
        'Morawewa',
        'Mulatiyana',
        'Mundalama',
        'Musalai',
        'Muttur',
        'Nachchadoowa',
        'Nagoda',
        'Nallur',
        'Nanaddan',
        'Narammala',
        'Nattandiya',
        'Naula',
        'Navithanveli',
        'Nawagattegama',
        'Negombo',
        'Neluwa',
        'Nikaweratiya',
        'Ninthavur',
        'Nivithigala',
        'Niyagama',
        'Nochchiyagama',
        'Nuwara Eliya',
        'Nuwaragam Palatha Central',
        'Nuwaragam Palatha East',
        'Oddusuddan',
        'Okewela',
        'Opanayaka',
        'Pachchilaipalli',
        'Padavi Sri Pura',
        'Padaviya',
        'Padiyathalawa',
        'Padukka',
        'Palagala',
        'Palindanuwara',
        'Pallama',
        'Pallepola',
        'Palugaswewa',
        'Panadura',
        'Panduwasnuwara',
        'Pannala',
        'Panvila',
        'Pasbage Korale',
        'Pasgoda',
        'Passara',
        'Pathadumbara',
        'Pathahewaheta',
        'Pelmadulla',
        'Pitabeddara',
        'Polgahawela',
        'Polpithigama',
        'Poojapitiya',
        'Poonakary',
        'Porativu Pattu',
        'Pothuvil',
        'Puthukudiyiruppu',
        'Puttalam',
        'Rajanganaya',
        'Rambewa',
        'Rambukkana',
        'Rasnayakapura',
        'Ratmalana',
        'Ratnapura',
        'Rattota',
        'Rideegama',
        'Rideemaliyadda',
        'Ruwanwella',
        'Sainthamarathu',
        'Samanthurai',
        'Seruvila',
        'Sevanagala',
        'Siyambalanduwa',
        'Sooriyawewa',
        'Soranathota',
        'Sri Jayawardanapura Kotte',
        'Tangalle',
        'Thalawa',
        'Thamankaduwa',
        'Thambalagamuwa',
        'Thambuttegama',
        'Thanamalvila',
        'Thawalama',
        'Thenmaradchi (Chavakachcheri)',
        'Thihagoda',
        'Thimbirigasyaya',
        'Thirappane',
        'Thirukkovil',
        'Thissamaharama',
        'Thumpane',
        'Thunukkai',
        'Trincomalee Town and Gravets',
        'Udadumbara',
        'Udapalatha',
        'Udubaddawa',
        'Udunuwara',
        'Uhana',
        'Ukuwela',
        'Uva-Paranagama',
        'Vadamaradchi East (Maruthnkerny)',
        'Vadamaradchi North (Point Pedro)',
        'Vadamaradchi South-West (Karaveddy)',
        'Valikamam East (Kopay)',
        'Valikamam North (Tellipallai)',
        'Valikamam South (Uduvil)',
        'Valikamam South-West (Sandilipay)',
        'Valikamam West (Chankanai)',
        'Vanathavilluwa',
        'Vavuniya',
        'Vavuniya North',
        'Vavuniya South',
        'Vengalacheddikulam',
        'Walallavita',
        'Walapane',
        'Warakapola',
        'Wariyapola',
        'Wattala',
        'Weeraketiya',
        'Weerambugedara',
        'Weligama',
        'Weligepola',
        'Welikanda',
        'Welimada',
        'Welioya',
        'Welipitiya',
        'Welivitiya-Divithura',
        'Wellawaya',
        'Wennappuwa',
        'Wilgamuwa',
        'Yakkalamulla',
        'Yatawatta',
        'Yatinuwara',
        'Yatiyanthota',
        'Verugal (Eechchilampattai)',
    ],
];
